name: Playwright Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [ chromium]

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Download Playwright
        uses: microsoft/playwright-action@v2

      - name: Run tests
        run: npx playwright test --browser=${{ matrix.browser }}
